<meta charset="utf-8">
<meta content="IE=edge" http-equiv="X-UA-Compatible">
<title>SMART SHRIMP Backend</title>
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- Bootstrap 3.3.7 -->
<link href="bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
<!-- Font Awesome -->
<link href="bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet">
<!-- Ionicons -->
<link href="bower_components/Ionicons/css/ionicons.min.css" rel="stylesheet">
<!-- Theme style -->
<link href="dist/css/AdminLTE.min.css" rel="stylesheet">
<!-- AdminLTE Skins. Choose a skin from the css/skins
     folder instead of downloading all of them to reduce the load. -->
<link href="dist/css/skins/_all-skins.min.css" rel="stylesheet">

<!-- Date Picker -->
<link href="bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet">
<!-- Bootstrap time Picker -->
<link href="plugins/timepicker/bootstrap-timepicker.min.css" rel="stylesheet">
<!-- Daterange picker -->
<link href="bower_components/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
<!-- bootstrap wysihtml5 - text editor -->
<link href="plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" rel="stylesheet">

<!-- Bootstrap Toggle -->
<link href="bower_components/bootstrap-toggle/css/bootstrap-toggle.min.css" rel="stylesheet">
<!-- bootstrap-dialog -->
<link href="bower_components/bootstrap3-dialog/dist/css/bootstrap-dialog.min.css" rel="stylesheet">

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic"
      rel="stylesheet">

<!-- jQuery 3 -->
<script src="bower_components/jquery/dist/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="bower_components/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<style>
    body.modal-open .modal {
        display: flex !important;
        height: 100%;
    }
    body.modal-open .modal .modal-dialog {
        margin: auto;
    }
    .box-body {
       padding: 20px;
    }
</style>